spring:
  profiles:
    active: local

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/smarteye}
    username: ${SPRING_DATASOURCE_USERNAME:smarteye}
    password: ${SPRING_DATASOURCE_PASSWORD:smarteye}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.smarteye.backend: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Для удобства локальной разработки можно ослабить CORS
CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://127.0.0.1:3000}

# Смещение между весами можно переопределить здесь
conveyor:
  offset-between-scales: ${CONVEYOR_OFFSET_BETWEEN_SCALES:5}
